spring:
  application:
    name: msvc-eureka
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}

server:
  port: ${EUREKA_SERVER_PORT:8761}

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${EUREKA_INSTANCE_HOSTNAME:localhost}:${EUREKA_SERVER_PORT:8761}/eureka/

management:
  metrics:
    binders:
      system:
        enabled: false
