server:
  port: 8084

springdoc:
  swagger-ui:
    path: /docs


spring:
  application:
    name: microservicio-peces
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql.railway.internal:3306/railway
    username: ${DB_USER:root}
    password: ${PECES_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO:update}
    database-platform: org.hibernate.dialect.MySQLDialect

eureka:
  instance:
    hostname: microservicio-peces.railway.internal
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://microservicio-eureka.railway.internal:8761/eureka}


