server:
  port: ${EUREKA_SERVER_PORT:8761}

spring:
  application:
    name: msvc-eureka

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
  client:
    register-with-eureka: false
    fetch-registry: false
  
management:
  metrics:
    binders:
      system:
        enabled: false